[versions]
spotless = "8.2.1"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version = "2.3.10" }
plugin-publish = { module = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin", version = "2.0.0" }
spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
